### ISSUE TITLE
AAD Créer un format d'instance pour le LLM répétable (cloud-init)

### ISSUE THREAD

**Issue by Acrend** [betagouv/VApp#15]
```[tasklist]
### Tasks
- [x] Créer le cloud-init et assurez-vous de son bon fonctionnement.
- [x] Créer un système d'authentification pour sécuriser l'instance
- [x] Créer script .sh que le cloud-init execute au lancement
```
