### ISSUE TITLE
AAU Je peux ameliorer l'eligibilite de mon projet à une aide

### ISSUE THREAD

**Issue by louispinot** [betagouv/VApp#25]
Un bouton "Affiner les résultats" présent sur la page de recommandations (cf [V5 Résultat](https://www.figma.com/design/zh7yWMHVDiLXKNMJ8avMqL/VAPP?node-id=233-8874&node-type=frame&t=zlp0ZL9lbDtcjG7y-0)) ouvre une modale conforme à [V5 Affinage step 1](https://www.figma.com/design/zh7yWMHVDiLXKNMJ8avMqL/VAPP?node-id=235-9598&node-type=frame&t=zlp0ZL9lbDtcjG7y-0) où l'utilisateur peut sélectionner une aide parmi celles recommandées. 

Cela déclenche la séquence décrite dans les tickets suivants:
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/VApp/issues/26
- [ ] https://github.com/betagouv/VApp/issues/27
- [ ] https://github.com/betagouv/VApp/issues/28
```

**Comment by louispinot** [comment]
@lutangar do you still need help on this issue? what help?
