### ISSUE TITLE
AAD Collecter les logs necessaires

### ISSUE THREAD

**Issue by Acrend** [betagouv/VApp#60]
```[tasklist]
### Tasks
- [ ] timestamp
- [ ] user_project_description_text : str
- [ ] user_project_description_id : str
- [ ] list_aides_id : list[str]
- [ ] scoring_list_aides : list[str]
```

**Comment by louispinot** [comment]
@lutangar @Acrend  TO DO explorer la faisabilité de collecter des ID de session

**Comment by lutangar** [comment]
https://stats.beta.gouv.fr

**Comment by louispinot** [comment]
> Voir si l'on peu trouver un identifiant de session dans Matomo https://stats.beta.gouv.fr

Je crois pas qu'on puisse le faire, car je n'ai trouvé rien en ce sens en ayant diggé la doc Matomo pdt 1h, et parce que leur critere pour identifier une visite unique, c'est si le visiteur a quitté le site depuis au moins 30min.

**Comment by louispinot** [comment]
C'est peut etre possible de passer la project-description ou bien le top-10-aides dans des trackers d'event matomo, mais je crois pas que ce soit le bon outil. Matomo est optimisé pour analyser les données d'usage. 
Si c'est pour log des données sur la pertinence de nos reco par rapprot aux descriptions des utilisateurs, je pense qu'il vaut mieux les faire remonter via un autre outil qui sera plus facile à requeter derriere. 

Si je lis juste la [desc de Sentry ici](https://doc.incubateur.net/communaute/les-outils-de-la-communaute/autres-services/sentry) j'ai pas l'impression que ce soit fait pour ca non plus
=> peut etre que si c'est pour alimenté le travail sur l'engine d'IA il faut stocker ces infos de façon custom via notre applicatif

**Comment by lutangar** [comment]
Economie de calcul possible en stock. score.
Table: descriptionProjet, aideId, compatibilite
